services:
  postgres:
    container_name: todo_postgres
    image: postgres
    environment:
      PGDATA: /var/lib/postgres/data
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: todo
      POSTGRES_USER: todo
      POSTGRES_DB: todo_db
    volumes:
       - todo_postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: todo_pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    todo_postgres:
    pgadmin: