"""empty message

Revision ID: 464518c62683
Revises: bd989c1d1031
Create Date: 2023-05-27 18:01:39.581680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464518c62683'
down_revision = 'bd989c1d1031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_logs_id'))

    op.drop_table('tasks_logs')
    # ### end Alembic commands ###
