"""empty message

Revision ID: b6bd84f36da3
Revises: 464518c62683
Create Date: 2023-05-27 18:10:20.519805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bd84f36da3'
down_revision = '464518c62683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_logs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_logs_task_id'))

    # ### end Alembic commands ###
