"""empty message

Revision ID: bd989c1d1031
Revises: de473b05129d
Create Date: 2023-05-27 17:54:35.088783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd989c1d1031'
down_revision = 'de473b05129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadlines')
    op.drop_table('subtasks')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.drop_column('complete')

    with op.batch_alter_table('tasks_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_groups_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('tasks_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_groups_group_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_column('parent_id')
        batch_op.drop_column('deadline')
        batch_op.drop_column('completed')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_user_id'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.create_table('subtasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('main_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtask_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['main_id'], ['tasks.id'], name='subtasks_main_id_fkey'),
    sa.ForeignKeyConstraint(['subtask_id'], ['tasks.id'], name='subtasks_subtask_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subtasks_pkey')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='deadlines_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deadlines_pkey')
    )
    # ### end Alembic commands ###
