"""empty message

Revision ID: c3ffc4af2e51
Revises: f4e5bbcc941b
Create Date: 2023-05-21 16:26:48.875212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ffc4af2e51'
down_revision = 'f4e5bbcc941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['tasks.id'], name='blocks_blocked_id_fkey'),
    sa.ForeignKeyConstraint(['blocking_id'], ['tasks.id'], name='blocks_blocking_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blocks_pkey')
    )
    # ### end Alembic commands ###
